# Site settings
title:       Roque Pinel
description: "Developer - Foodie - Traveler"
baseurl:     "" # the subpath of your site, e.g. /blog
url:         "http://www.pinel.cc"

# Google analytics
google_analytics: "UA-21761105-1"

# Social Media settings
github_username:   repinel
github_user_id:    1685896
linkedin_username: roquepinel
twitter_username:  repinel

# Build settings
gems:
  - jekyll-paginate
  - jemoji

markdown:         kramdown
permalink:        "/blog/:year/:month/:day/:title"
blog_assets_path: "/blog/assets"
paginate_path:    "/blog/page/:num"
paginate:         10

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - script
